export type CampaignLocale = "ar" | "en";

export const campaignCopy = {
  ar: {
    direction: "rtl",
    locale: "ar-SA",
    common: {
      campaigns: "الحملات",
      back: "رجوع",
      view: "عرض التفاصيل",
      create: "إنشاء حملة",
      search: "بحث",
      all: "الكل",
      currency: "ر.س",
      unspecified: "غير محدد",
      noData: "لا توجد بيانات",
      save: "حفظ",
      cancel: "إلغاء",
      next: "التالي",
      previous: "السابق",
      loading: "جاري التحميل...",
    },
    statuses: {
      draft: "مسودة",
      active: "نشطة",
      paused: "موقوفة مؤقتًا",
      completed: "مكتملة",
      archived: "مؤرشفة",
    },
    list: {
      title: "إدارة الحملات",
      subtitle: "تابعي الحملات والميزانيات والمؤثرين من مكان واحد.",
      newCampaign: "حملة جديدة",
      total: "إجمالي الحملات",
      active: "الحملات النشطة",
      draft: "المسودات",
      completed: "المكتملة",
      totalBudget: "إجمالي الميزانيات",
      searchPlaceholder: "ابحثي باسم الحملة أو البراند أو المنتج",
      filterStatus: "حالة الحملة",
      campaign: "الحملة",
      manager: "مدير الحملة",
      dates: "المدة",
      influencers: "المؤثرون",
      progress: "الإنجاز",
      budget: "الميزانية",
      status: "الحالة",
      actions: "الإجراءات",
      noCampaigns: "لا توجد حملات مطابقة للبحث الحالي.",
      allStatuses: "جميع الحالات",
      createdSuccess: "تم إنشاء الحملة بنجاح.",
    },
    form: {
      title: "إنشاء حملة جديدة",
      subtitle: "أنشئي بريفًا واضحًا ثم أضيفي المؤثرين والتعاون والمقابل.",
      section1: "البيانات الأساسية",
      section1Hint: "اسم الحملة والبراند والمنتج والهدف.",
      section2: "المواعيد والميزانية",
      section2Hint: "الإطار الزمني والميزانية التقديرية للحملة.",
      section3: "حالة الحملة",
      section3Hint: "اختاري المرحلة التي تبدأ منها الحملة.",
      section4: "التفاصيل المساندة",
      section4Hint: "الهاشتاقات والمراجع والملاحظات الداخلية.",
      name: "اسم الحملة",
      namePlaceholder: "مثال: صيف روماند 2026",
      brand: "البراند",
      brandPlaceholder: "اختاري أو اكتبي البراند",
      product: "المنتج أو المجموعة",
      productPlaceholder: "مثال: Juicy Lasting Tint",
      type: "نوع الحملة",
      typePlaceholder: "اختاري نوع الحملة",
      brief: "وصف وبريف الحملة",
      briefPlaceholder: "الهدف، الرسالة الرئيسية، الجمهور، المطلوب من المؤثر وأي تعليمات مهمة...",
      startDate: "تاريخ البداية",
      endDate: "تاريخ النهاية",
      contentDue: "موعد تسليم المحتوى",
      publishingDate: "موعد النشر",
      budget: "الميزانية التقديرية",
      manager: "مدير الحملة",
      you: "أنتِ",
      hashtags: "الهاشتاقات",
      hashtagsPlaceholder: "#romand، #تنت\nيمكن الفصل بفاصلة أو سطر جديد",
      references: "الروابط المرجعية",
      referencesPlaceholder: "https://...\nhttps://...",
      notes: "ملاحظات داخلية للفريق",
      notesPlaceholder: "لا تظهر هذه الملاحظات للمؤثر، وتستخدم للتنسيق الداخلي فقط.",
      createButton: "إنشاء الحملة",
      creating: "جاري إنشاء الحملة...",
      nextStep: "بعد الحفظ يمكنك إضافة المؤثرين وتحديد تفاصيل التعاون والمقابل.",
      statusDraftDescription: "تجهيز داخلي قبل بدء العمل",
      statusActiveDescription: "الحملة جاهزة للتنفيذ",
      statusPausedDescription: "توقف مؤقت مع حفظ البيانات",
    },
    details: {
      back: "العودة للحملات",
      addInfluencer: "إضافة مؤثر للحملة",
      manager: "مدير الحملة",
      influencerCount: "عدد المؤثرين",
      publishDate: "موعد النشر",
      estimatedBudget: "الميزانية التقديرية",
      committed: "المبلغ المرتبط",
      remaining: "المتبقي",
      paid: "المدفوع",
      awaiting: "بانتظار الدفع",
      overBudget: "تجاوز الميزانية",
      usage: "استخدام الميزانية",
      campaignBrief: "بريف الحملة",
      timeline: "الجدول الزمني",
      startDate: "بداية الحملة",
      endDate: "نهاية الحملة",
      contentDue: "تسليم المحتوى",
      assignments: "المؤثرون المرتبطون",
      noAssignments: "لم تتم إضافة مؤثرين إلى الحملة بعد.",
      influencer: "المؤثر",
      collaboration: "التعاون",
      platforms: "المنصات والمحتوى",
      compensation: "المقابل",
      assignmentStatus: "حالة التكليف",
      contract: "العقد",
      yes: "نعم",
      no: "لا",
      home: "منزلي",
      inBranch: "حضوري",
      other: "أخرى",
      orderNumber: "رقم الطلب",
      orderCode: "كود الطلب",
      orderAmount: "قيمة الطلب",
      branch: "الفرع",
      attendance: "موعد الحضور",
      contractPayment: "مرتبط بعقد",
      hashtags: "الهاشتاقات",
      internalNotes: "ملاحظات داخلية",
      references: "روابط مرجعية",
      createdSuccess: "تم إنشاء الحملة وحفظ بياناتها بنجاح.",
      assignmentSuccess: "تم ربط المؤثر بالحملة وحفظ تفاصيل التعاون والمقابل.",
      budgetWarning: "تم تجاوز الميزانية التقديرية، لكن النظام يسمح باستمرار العمل.",
    },
    add: {
      title: "إضافة مؤثر للحملة",
      subtitle: "اختاري المؤثر ثم حددي التعاون والمقابل في ثلاث خطوات.",
      availabilityRule: "لا يمكن ربط المؤثر بحملة أخرى أثناء تكليف قائم أو قبل مرور 45 يومًا على تسوية آخر مستحقاته.",
      branchWarning: "تعذر تحميل قائمة الفروع. يمكنك كتابة فرع جديد وسيُحفظ عند إنشاء التكليف.",
    },
  },
  en: {
    direction: "ltr",
    locale: "en-US",
    common: {
      campaigns: "Campaigns",
      back: "Back",
      view: "View details",
      create: "Create campaign",
      search: "Search",
      all: "All",
      currency: "SAR",
      unspecified: "Not set",
      noData: "No data",
      save: "Save",
      cancel: "Cancel",
      next: "Next",
      previous: "Previous",
      loading: "Loading...",
    },
    statuses: {
      draft: "Draft",
      active: "Active",
      paused: "Paused",
      completed: "Completed",
      archived: "Archived",
    },
    list: {
      title: "Campaign Management",
      subtitle: "Track campaigns, budgets and influencers in one workspace.",
      newCampaign: "New campaign",
      total: "Total campaigns",
      active: "Active campaigns",
      draft: "Drafts",
      completed: "Completed",
      totalBudget: "Total budgets",
      searchPlaceholder: "Search by campaign, brand or product",
      filterStatus: "Campaign status",
      campaign: "Campaign",
      manager: "Campaign manager",
      dates: "Dates",
      influencers: "Influencers",
      progress: "Progress",
      budget: "Budget",
      status: "Status",
      actions: "Actions",
      noCampaigns: "No campaigns match the current filters.",
      allStatuses: "All statuses",
      createdSuccess: "Campaign created successfully.",
    },
    form: {
      title: "Create a New Campaign",
      subtitle: "Create a clear brief, then add influencers, collaboration and compensation.",
      section1: "Basic information",
      section1Hint: "Campaign name, brand, product and objective.",
      section2: "Dates and budget",
      section2Hint: "Campaign timeline and estimated budget.",
      section3: "Campaign status",
      section3Hint: "Choose the stage the campaign starts from.",
      section4: "Supporting details",
      section4Hint: "Hashtags, references and internal notes.",
      name: "Campaign name",
      namePlaceholder: "Example: Rom&nd Summer 2026",
      brand: "Brand",
      brandPlaceholder: "Select or type a brand",
      product: "Product or collection",
      productPlaceholder: "Example: Juicy Lasting Tint",
      type: "Campaign type",
      typePlaceholder: "Select a campaign type",
      brief: "Campaign brief",
      briefPlaceholder: "Objective, key message, audience, influencer requirements and instructions...",
      startDate: "Start date",
      endDate: "End date",
      contentDue: "Content due date",
      publishingDate: "Publishing date",
      budget: "Estimated budget",
      manager: "Campaign manager",
      you: "You",
      hashtags: "Hashtags",
      hashtagsPlaceholder: "#romand, #tint\nSeparate with commas or new lines",
      references: "Reference links",
      referencesPlaceholder: "https://...\nhttps://...",
      notes: "Internal team notes",
      notesPlaceholder: "These notes are private to the internal team.",
      createButton: "Create campaign",
      creating: "Creating campaign...",
      nextStep: "After saving, add influencers and define collaboration and compensation.",
      statusDraftDescription: "Internal preparation before launch",
      statusActiveDescription: "Campaign is ready for execution",
      statusPausedDescription: "Temporarily paused while keeping data",
    },
    details: {
      back: "Back to campaigns",
      addInfluencer: "Add influencer",
      manager: "Campaign manager",
      influencerCount: "Influencers",
      publishDate: "Publishing date",
      estimatedBudget: "Estimated budget",
      committed: "Committed",
      remaining: "Remaining",
      paid: "Paid",
      awaiting: "Awaiting payment",
      overBudget: "Over budget",
      usage: "Budget usage",
      campaignBrief: "Campaign brief",
      timeline: "Timeline",
      startDate: "Campaign start",
      endDate: "Campaign end",
      contentDue: "Content due",
      assignments: "Assigned influencers",
      noAssignments: "No influencers have been added yet.",
      influencer: "Influencer",
      collaboration: "Collaboration",
      platforms: "Platforms and content",
      compensation: "Compensation",
      assignmentStatus: "Assignment status",
      contract: "Contract",
      yes: "Yes",
      no: "No",
      home: "Home",
      inBranch: "In branch",
      other: "Other",
      orderNumber: "Order number",
      orderCode: "Order code",
      orderAmount: "Order value",
      branch: "Branch",
      attendance: "Attendance",
      contractPayment: "Contracted",
      hashtags: "Hashtags",
      internalNotes: "Internal notes",
      references: "Reference links",
      createdSuccess: "Campaign and its details were created successfully.",
      assignmentSuccess: "Influencer, collaboration and compensation details were saved.",
      budgetWarning: "The estimated budget has been exceeded, but work can continue.",
    },
    add: {
      title: "Add Influencer to Campaign",
      subtitle: "Choose an influencer, then define collaboration and compensation in three steps.",
      availabilityRule: "An influencer cannot join another campaign during an active assignment or within 45 days after the final settlement.",
      branchWarning: "Branches could not be loaded. You can type a new branch and it will be saved with the assignment.",
    },
  },
} as const;

export function getCampaignCopy(locale: CampaignLocale) {
  return campaignCopy[locale];
}
