import Link from "next/link";
import { requireRole } from "@/lib/auth/require-user";
export const dynamic = "force-dynamic";
const statusLabels:Record<string,string>={pending:"بانتظار المراجعة",needs_changes:"مطلوب تعديل",approved:"بانتظار التفعيل",completed:"مفعّل",rejected:"مرفوض",cancelled:"ملغي"};
export default async function AccessRequestsPage(){
 const {supabase,profile}=await requireRole(["admin","coordinator","finance"]);
 const {data:requests}=await supabase.from("portal_access_requests").select("id,requested_email,normalized_mobile,status,priority,created_at,influencers(full_name,profile_completion,user_id,archive_match_status)").order("created_at",{ascending:false});
 return <main dir="rtl" className="min-h-screen bg-[#F4F6FB] p-4 sm:p-8 text-[#33447F]"><div className="mx-auto max-w-7xl"><div className="mb-6 flex items-center justify-between"><div><p className="text-sm font-black text-[#6877C8]">بوابة المؤثر</p><h1 className="mt-1 text-3xl font-black">طلبات تفعيل الحساب</h1><p className="mt-2 text-sm font-semibold text-[#7E87A1]">المراجعة والتفعيل تتم بدون إرسال بريد إلكتروني للمؤثر.</p></div><Link href="/dashboard" className="rounded-xl border bg-white px-4 py-2 font-black">العودة</Link></div>{profile.role!=="admin"?<div className="mb-5 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm font-bold text-blue-800">يمكنك مشاهدة الطلبات، بينما الاعتماد وطلب التعديل والرفض للمدير فقط.</div>:null}<section className="overflow-hidden rounded-[26px] border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-[#F1F3FB]"><tr>{["المؤثر","الجوال","البريد","اكتمال الملف","الأرشيف","الحالة","التاريخ","الإجراء"].map(h=><th key={h} className="p-4 text-right">{h}</th>)}</tr></thead><tbody>{(requests||[]).map(r=>{const i=Array.isArray(r.influencers)?r.influencers[0]:r.influencers;return <tr key={r.id} className="border-t"><td className="p-4 font-black">{i?.full_name||"—"}</td><td dir="ltr" className="p-4">{r.normalized_mobile}</td><td dir="ltr" className="p-4">{r.requested_email}</td><td className="p-4">{i?.profile_completion??0}%</td><td className="p-4">{i?.archive_match_status==="matched"?"مطابقة محتملة":"—"}</td><td className="p-4"><span className="rounded-full bg-[#EEF0FB] px-3 py-1.5 text-xs font-black">{statusLabels[r.status]||r.status}</span></td><td className="p-4">{new Date(r.created_at).toLocaleDateString("ar-SA")}</td><td className="p-4"><Link href={`/dashboard/access-requests/${r.id}`} className="rounded-xl bg-[#6575CB] px-4 py-2 font-black text-white">مراجعة التفاصيل</Link></td></tr>})}</tbody></table></div></section></div></main>
}
