import { NextResponse } from "next/server";
import { z } from "zod";
import { createAdminClient } from "@/lib/supabase/admin";
import { hashPortalToken } from "@/lib/portal-access/tokens";
export const dynamic="force-dynamic";
const schema=z.object({token:z.string().min(20),password:z.string().min(8).max(128).regex(/[A-Za-z]/,"كلمة المرور يجب أن تحتوي على حرف").regex(/[0-9]/,"كلمة المرور يجب أن تحتوي على رقم")});
async function lookup(token:string){const admin=createAdminClient();const {data}=await admin.from("portal_access_tokens").select("id,request_id,created_by,expires_at,used_at,revoked_at,portal_access_requests(id,influencer_id,requested_email,status,influencers(id,user_id,full_name,mobile_e164))").eq("token_hash",hashPortalToken(token)).eq("purpose","activation").maybeSingle();if(!data||data.used_at||data.revoked_at||new Date(data.expires_at).getTime()<Date.now())return null;return{admin,data}}
export async function GET(request:Request){try{const token=new URL(request.url).searchParams.get("token")||"";const found=await lookup(token);if(!found)return NextResponse.json({message:"رابط التفعيل غير صالح أو منتهي"},{status:410});const req:any=Array.isArray(found.data.portal_access_requests)?found.data.portal_access_requests[0]:found.data.portal_access_requests;if(!req||req.status!=="approved")return NextResponse.json({message:"طلب التفعيل غير متاح"},{status:409});const i:any=Array.isArray(req.influencers)?req.influencers[0]:req.influencers;return NextResponse.json({fullName:i?.full_name||"المؤثر",email:req.requested_email})}catch{return NextResponse.json({message:"تعذر التحقق من الرابط"},{status:500})}}
export async function POST(request:Request){try{const parsed=schema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({message:parsed.error.issues[0]?.message||"البيانات غير صحيحة"},{status:400});const found=await lookup(parsed.data.token);if(!found)return NextResponse.json({message:"رابط التفعيل غير صالح أو منتهي"},{status:410});const req:any=Array.isArray(found.data.portal_access_requests)?found.data.portal_access_requests[0]:found.data.portal_access_requests;if(!req||req.status!=="approved")return NextResponse.json({message:"الطلب غير متاح للتفعيل"},{status:409});const i:any=Array.isArray(req.influencers)?req.influencers[0]:req.influencers;if(!i||i.user_id)return NextResponse.json({message:"الحساب مفعّل مسبقًا"},{status:409});
 const {data:userData,error:userError}=await found.admin.auth.admin.createUser({email:req.requested_email,password:parsed.data.password,email_confirm:true,user_metadata:{full_name:i.full_name,mobile_e164:i.mobile_e164,role:"influencer"}});if(userError||!userData.user){const m=userError?.message?.toLowerCase()||"";return NextResponse.json({message:m.includes("already")?"البريد مرتبط بحساب آخر. تواصل مع الإدارة.":"تعذر إنشاء الحساب"},{status:409})}
 const uid=userData.user.id;const {error:linkError}=await found.admin.rpc("link_influencer_portal_invitation",{p_request_id:req.id,p_influencer_id:req.influencer_id,p_user_id:uid,p_approved_by:found.data.created_by,p_email:req.requested_email});if(linkError){await found.admin.auth.admin.deleteUser(uid);throw linkError}const {error:completeError}=await found.admin.rpc("complete_influencer_portal_activation",{p_user_id:uid});if(completeError)throw completeError;const now=new Date().toISOString();await found.admin.from("portal_access_tokens").update({used_at:now}).eq("id",found.data.id);await found.admin.from("influencers").update({activation_status:"active",account_activated_at:now,must_change_password:false}).eq("id",req.influencer_id);return NextResponse.json({success:true,nextPath:"/login?activated=1"})
 }catch(e){console.error("portal activation",e);return NextResponse.json({message:"تعذر تفعيل الحساب حاليًا"},{status:500})}}
